name: build

on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install composer packages
        run: composer install --no-dev
      - name: Run tests
        run: ./runtime test
      
      - name: Build application 
        run: ./runtime app:build --build-version= 
      
